<#
.SYNOPSIS
    Generate the Vela side of the LLVM shim's interface from its C header.

.DESCRIPTION
    `runtime\vela_llvm_shim.c` is the compiler's own code generator: a pure-C API over
    `llvm-c`, which the Vela compiler reaches through `extern c` declarations.  Those
    declarations are the interface, and an interface written twice by hand is an
    interface that drifts 閳?one side grows a function, the other does not, and the
    failure appears later as a symbol the linker cannot find in a file nobody edited.

    So the Vela side is **generated** from the header, and this script also checks it:
    with `-Check` it regenerates in memory and fails if the file on disk differs, which
    is what makes "the two agree" a fact rather than an intention.

    The type mapping is the compiler's own, read out of `emit_ctype`
    (`selfhost\parts\emit.vel:177`), so a declaration here produces the C the header
    declares:

        int64_t  -> int       int32_t -> i32      uint8_t -> u8
        double   -> float     bool    -> bool     vela_str -> str
        void     -> None

.PARAMETER Check
    Do not write; fail (exit 1) if `selfhost\parts\llvm_shim.vel` is not what the
    header would generate right now.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File tools\gen-shim-decls.ps1
    powershell -ExecutionPolicy Bypass -File tools\gen-shim-decls.ps1 -Check
#>
[CmdletBinding()]
param(
    [switch] $Check
)

$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent $PSScriptRoot
$header = Join-Path $repo 'runtime\vela_llvm_shim.h'
# Staged under selfhost\llvm\ rather than selfhost\parts\, and that is deliberate:
# `tools\build.ps1` now refuses to build when a file in parts\ is not in the linker's
# part list, and registering this one today would break the build, because `extern c`
# refuses `str` parameters (check.vel:2580) and six of the 48 declarations take one
# (`module_open`, `fn_declare`, `fn_define`, `string_global`, `block_append`,
# `emit_object`).  The file moves into parts\ and gets its part_name() entry in the
# same change that allows a `str` parameter -- and until then it is an interface on
# paper, not a part of the compiler.  Measured: with those six filtered out the other
# 42 type-check (`vm.exe check` → `ok`, exit 0), so the mapping table itself is right.
$out = Join-Path $repo 'selfhost\llvm\llvm_shim.vel'

if (-not (Test-Path -LiteralPath $header)) { throw "no shim header at $header" }
$text = Get-Content -LiteralPath $header -Raw

# Every declaration of the form `<type> vshim_...(params);`.  The header is the
# source of truth; nothing here invents a function.
$pattern = '(?m)^(int32_t|int64_t|double|void|bool)\s+(vshim_[a-z0-9_]+)\s*\(([^;]*)\);'
$decls = [regex]::Matches($text, $pattern)
if ($decls.Count -eq 0) { throw "no vshim_* declarations found in $header" }

function Convert-Type([string] $c, [string] $name) {
    switch ($c.Trim()) {
        'int64_t' { return "${name}: int" }
        'int32_t' { return "${name}: i32" }
        'uint8_t' { return "${name}: u8" }
        'double'  { return "${name}: float" }
        'bool'    { return "${name}: bool" }
        'vela_str' { return "${name}: str" }
        default   { throw "no Vela spelling for the C type '$c' in parameter '$name'" }
    }
}

function Convert-Return([string] $c) {
    switch ($c.Trim()) {
        'int64_t' { return 'int' }
        'int32_t' { return 'i32' }
        'uint8_t' { return 'u8' }
        'double'  { return 'float' }
        'bool'    { return 'bool' }
        'vela_str' { return 'str' }
        'void'    { return 'None' }
        default   { throw "no Vela spelling for the C return type '$c'" }
    }
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('# ============================================================================')
$lines.Add('# llvm_shim.vel -- the Vela side of the compiler''s own code generator.')
$lines.Add('#')
$lines.Add('# GENERATED by tools\gen-shim-decls.ps1 from runtime\vela_llvm_shim.h.')
$lines.Add('# Do not edit by hand: edit the header and regenerate, or the two sides drift')
$lines.Add('# and the failure surfaces as an undefined symbol in a file nobody touched.')
$lines.Add('#')
$lines.Add('# This is the bridge that makes the north star reachable: `vm.exe` carries')
$lines.Add('# libLLVM inside it (through these calls) instead of shelling out to a C')
$lines.Add('# compiler, so `vm.exe build x.vel` can write an object file itself and leave')
$lines.Add('# only the executable in the user''s directory.')
$lines.Add('#')
$lines.Add('# The C types map by the compiler''s own rule (emit_ctype, emit.vel:177):')
$lines.Add('# int64_t -> int, int32_t -> i32, uint8_t -> u8, double -> float,')
$lines.Add('# bool -> bool, vela_str -> str, void -> None.')
$lines.Add('#')
$lines.Add("# $($decls.Count) declarations, in the header's order.")
$lines.Add('# ============================================================================')
$lines.Add('')
$lines.Add('# Handles (modules, types, functions, blocks, values) are `int` here because')
$lines.Add('# they are opaque pointers in C: the emitter passes them back unchanged and')
$lines.Add('# never looks inside one.')
$lines.Add('')

foreach ($d in $decls) {
    $ret = Convert-Return $d.Groups[1].Value
    $fn  = $d.Groups[2].Value
    $paramsText = $d.Groups[3].Value.Trim()
    if ($paramsText -eq '' -or $paramsText -eq 'void') {
        $lines.Add("extern c def $fn() -> $ret")
        continue
    }
    $parts = @()
    foreach ($p in $paramsText -split ',') {
        $p = $p.Trim()
        # `<type> <name>`; the header names every parameter, so there is no
        # unnamed-parameter case to guess at.
        $m = [regex]::Match($p, '^(int32_t|int64_t|double|bool|uint8_t|vela_str)\s+([a-z0-9_]+)$')
        if (-not $m.Success) {
            if ($p -match '^\.\.\.$') {
                # varargs: Vela has no spelling for them, and the shim has none
                # either -- a call the emitter cannot typecheck is a call the
                # emitter must not make.
                throw "variadic parameter in ${fn}: the interface must stay typable"
            }
            throw "cannot read the parameter '$p' of ${fn}"
        }
        $parts += (Convert-Type $m.Groups[1].Value $m.Groups[2].Value)
    }
    $lines.Add("extern c def $fn($($parts -join ', ')) -> $ret")
}

$lines.Add('')
$generated = ($lines -join "`n") + "`n"

if ($Check) {
    if (-not (Test-Path -LiteralPath $out)) {
        Write-Host "MISSING: $out does not exist; run this script without -Check" -ForegroundColor Red
        exit 1
    }
    $current = Get-Content -LiteralPath $out -Raw
    if ($current -ne $generated) {
        Write-Host "STALE: $out is not what runtime\vela_llvm_shim.h generates now" -ForegroundColor Red
        $curLines = $current -split "`n"
        $genLines = $generated -split "`n"
        $n = [Math]::Min($curLines.Count, $genLines.Count)
        for ($i = 0; $i -lt $n; $i++) {
            if ($curLines[$i] -ne $genLines[$i]) {
                Write-Host ("  first difference at line {0}:" -f ($i + 1))
                Write-Host ("    on disk: {0}" -f $curLines[$i])
                Write-Host ("    header : {0}" -f $genLines[$i])
                break
            }
        }
        Write-Host ("  ($($decls.Count) declarations in the header)")
        exit 1
    }
    Write-Host "in step: $out matches runtime\vela_llvm_shim.h ($($decls.Count) declarations)"
    exit 0
}

[System.IO.File]::WriteAllText($out, $generated, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "wrote $out"
Write-Host "  $($decls.Count) declarations from runtime\vela_llvm_shim.h"
