/* Generated by the self-hosted Vela compiler.  Every bounds and
 * overflow check below is emitted on purpose: this back end has no
 * checker yet, so it proves nothing away.  The program it came from
 * is Vela source, and this file is its meaning in C11. */
#include "vela_runtime.h"
#include <stdbool.h>

static vela_str vl_lexer_path(void);
static vela_str vl_parts_dir(void);
static vela_str vl_out_path(void);
static vela_str vl_driver_marker(void);
static int64_t vl_part_count(void);
static vela_str vl_part_name(int64_t);
static vela_str vl_banner(void);
static bool vl_is_space(int64_t);
static vela_str vl_rstrip(vela_str);
static int64_t vl_find(vela_str, vela_str);
static int64_t vl_n_nl(vela_str);
static vela_str vl_rule(int64_t);
static vela_str vl_part_header(vela_str);
static vela_str vl_link(void);
static void vl_main(void);

static vela_str vl_lexer_path(void) {
    return vela_str_lit("selfhost/vela.vel", 17);
}

static vela_str vl_parts_dir(void) {
    return vela_str_lit("selfhost/parts/", 15);
}

static vela_str vl_out_path(void) {
    return vela_str_lit("selfhost/vm.vel", 15);
}

static vela_str vl_driver_marker(void) {
    return vela_str_lit("\n# driver\n", 10);
}

static int64_t vl_part_count(void) {
    return 8LL;
}

static vela_str vl_part_name(int64_t vl_i) {
    if ((vl_i == 0LL)) {
        return vela_str_lit("vm_state.vel", 12);
    }
    if ((vl_i == 1LL)) {
        return vela_str_lit("parser.vel", 10);
    }
    if ((vl_i == 2LL)) {
        return vela_str_lit("resolve.vel", 11);
    }
    if ((vl_i == 3LL)) {
        return vela_str_lit("check.vel", 9);
    }
    if ((vl_i == 4LL)) {
        return vela_str_lit("eval.vel", 8);
    }
    if ((vl_i == 5LL)) {
        return vela_str_lit("emit.vel", 8);
    }
    if ((vl_i == 6LL)) {
        return vela_str_lit("dump.vel", 8);
    }
    if ((vl_i == 7LL)) {
        return vela_str_lit("vm_main.vel", 11);
    }
    return vela_str_lit("", 0);
}

static vela_str vl_banner(void) {
    return vela_str_lit("# ============================================================================\n# selfhost/vm.vel - GENERATED by tools/link_selfhost.vel.  Do not edit: edit\n# the parts and re-link.\n#\n# The self-hosted front end of Vela, in one file because Vela 0.1 has no module\n# system: the lexer (from selfhost/vela.vel), then the interpreter's shared\n# state, the parser, the resolver, the checker, the evaluator, the C11 emitter,\n# the syntax-tree dumper, and the driver that puts them behind one command.\n#\n#     selfhost/build/vm.exe build tools/link_selfhost.vel && tools/link_selfhost.exe\n#     selfhost/build/vm.exe build selfhost/vm.vel\n#     selfhost/build/vm.exe lex   bench/matmul.vel\n#     selfhost/build/vm.exe parse selfhost/parts/parser.vel\n#     selfhost/build/vm.exe run   tests/build/recursion_fib.vel\n# ============================================================================\n\n", 887);
}

static bool vl_is_space(int64_t vl_c) {
    if ((vl_c == 32LL)) {
        return true;
    }
    if ((vl_c == 9LL)) {
        return true;
    }
    if ((vl_c == 10LL)) {
        return true;
    }
    if ((vl_c == 13LL)) {
        return true;
    }
    return false;
}

static vela_str vl_rstrip(vela_str vl_s) {
    int64_t vl_e = (((int64_t)vl_s.len));
    while ((vl_e > 0LL)) {
        if ((!vl_is_space((vela_bytes_at(vl_s, vela_sub_range((vl_e), (1LL), INT64_MIN, INT64_MAX, "tools/link_selfhost.vel", 72), "tools/link_selfhost.vel", 72))))) {
            break;
        }
        vl_e = vela_sub_range(vl_e, 1LL, INT64_MIN, INT64_MAX, "tools/link_selfhost.vel", 75);
    }
    return (vela_substr(vl_s, 0LL, vl_e));
}

static int64_t vl_find(vela_str vl_s, vela_str vl_needle) {
    int64_t vl_n = (((int64_t)vl_needle.len));
    if ((vl_n == 0LL)) {
        return 0LL;
    }
    int64_t vl_i = 0LL;
    while ((vela_add_range((vl_i), (vl_n), INT64_MIN, INT64_MAX, "tools/link_selfhost.vel", 87) <= (((int64_t)vl_s.len)))) {
        if ((vela_str_eq((vela_substr(vl_s, vl_i, vela_add_range((vl_i), (vl_n), INT64_MIN, INT64_MAX, "tools/link_selfhost.vel", 88))), vl_needle))) {
            return vl_i;
        }
        vl_i = vela_add_range(vl_i, 1LL, INT64_MIN, INT64_MAX, "tools/link_selfhost.vel", 91);
    }
    return vela_sub_range((0LL), (1LL), INT64_MIN, INT64_MAX, "tools/link_selfhost.vel", 93);
}

static int64_t vl_n_nl(vela_str vl_s) {
    int64_t vl_n = 0LL;
    int64_t vl_i = 0LL;
    while ((vl_i < (((int64_t)vl_s.len)))) {
        if (((vela_bytes_at(vl_s, vl_i, "tools/link_selfhost.vel", 100)) == 10LL)) {
            vl_n = vela_add_range(vl_n, 1LL, INT64_MIN, INT64_MAX, "tools/link_selfhost.vel", 101);
        }
        vl_i = vela_add_range(vl_i, 1LL, INT64_MIN, INT64_MAX, "tools/link_selfhost.vel", 103);
    }
    return vl_n;
}

static vela_str vl_rule(int64_t vl_n) {
    int64_t vl_k = vela_sub_range((66LL), (vl_n), INT64_MIN, INT64_MAX, "tools/link_selfhost.vel", 112);
    if ((vl_k < 4LL)) {
        vl_k = 4LL;
    }
    vela_str vl_r = vela_str_lit("", 0);
    int64_t vl_i = 0LL;
    while ((vl_i < vl_k)) {
        vl_r = (vela_concat(vl_r, vela_str_lit("=", 1)));
        vl_i = vela_add_range(vl_i, 1LL, INT64_MIN, INT64_MAX, "tools/link_selfhost.vel", 120);
    }
    return vl_r;
}

static vela_str vl_part_header(vela_str vl_name) {
    return (vela_concat((vela_concat(vela_str_lit("\n# ==== ", 8), (vela_concat(vl_parts_dir(), vl_name)))), (vela_concat(vela_str_lit(" ", 1), (vela_concat(vl_rule((((int64_t)vl_name.len))), vela_str_lit("\n", 1)))))));
}

static vela_str vl_link(void) {
    vela_str vl_src = (vela_read_text(vl_lexer_path()));
    if (((((int64_t)vl_src.len)) == 0LL)) {
        (void)((vela_panic_str(vela_str_lit("link_selfhost: cannot read selfhost/vela.vel", 44))));
    }
    int64_t vl_at = vl_find(vl_src, vl_driver_marker());
    if ((vl_at < 0LL)) {
        (void)((vela_panic_str(vela_str_lit("link_selfhost: selfhost/vela.vel has no '# driver' marker - did the lexer's driver section move?", 96))));
    }
    vela_str vl_out = vl_banner();
    vl_out = (vela_concat(vl_out, (vela_concat(vl_rstrip((vela_substr(vl_src, 0LL, vl_at))), vela_str_lit("\n", 1)))));
    int64_t vl_i = 0LL;
    while ((vl_i < vl_part_count())) {
        vela_str vl_name = vl_part_name(vl_i);
        vela_str vl_body = (vela_read_text((vela_concat(vl_parts_dir(), vl_name))));
        if (((((int64_t)vl_body.len)) == 0LL)) {
            (void)((vela_panic_str((vela_concat(vela_str_lit("link_selfhost: cannot read ", 27), (vela_concat(vl_parts_dir(), vl_name)))))));
        }
        vl_out = (vela_concat(vl_out, vl_part_header(vl_name)));
        vl_out = (vela_concat(vl_out, (vela_concat(vl_rstrip(vl_body), vela_str_lit("\n", 1)))));
        vl_i = vela_add_range(vl_i, 1LL, INT64_MIN, INT64_MAX, "tools/link_selfhost.vel", 151);
    }
    return vl_out;
}

static void vl_main(void) {
    bool vl_check = false;
    if (((vela_argc()) >= 2LL)) {
        if ((vela_str_eq((vela_arg(1LL, "tools/link_selfhost.vel", 160)), vela_str_lit("--check", 7)))) {
            vl_check = true;
        }
    }
    vela_str vl_text = vl_link();
    if (vl_check) {
        vela_str vl_have = (vela_read_text(vl_out_path()));
        if ((vela_str_eq(vl_have, vl_text))) {
            (void)((vela_emit_str(vl_out_path())));
            (void)((vela_emit_str(vela_str_lit(" is up to date", 14))));
            (void)((vela_emit_nl()));
            return;
        }
        (void)((vela_warn_str(vela_str_lit("link_selfhost: ", 15))));
        (void)((vela_warn_str(vl_out_path())));
        (void)((vela_warn_str(vela_str_lit(" is stale: run `vm.exe run tools/link_selfhost.vel`", 51))));
        (void)((vela_warn_nl()));
        (void)((vela_panic_str(vela_str_lit("the linked compiler is out of date", 34))));
    }
    if ((!(((bool)vela_write_text(vl_out_path(), vl_text))))) {
        (void)((vela_panic_str(vela_str_lit("link_selfhost: could not write selfhost/vm.vel", 46))));
    }
    (void)((vela_emit_str(vela_str_lit("linked ", 7))));
    (void)((vela_emit_str(vl_out_path())));
    (void)((vela_emit_str(vela_str_lit(": ", 2))));
    (void)((vela_emit_int(vl_n_nl(vl_text))));
    (void)((vela_emit_str(vela_str_lit(" lines, ", 8))));
    (void)((vela_emit_int((((int64_t)vl_text.len)))));
    (void)((vela_emit_str(vela_str_lit(" bytes", 6))));
    (void)((vela_emit_nl()));
}

int main(int argc, char **argv) {
    vela_set_args(argc, argv);
    vela_runtime_init();
    vl_main();
    return 0;
}
